In [1]:
import pandas as pd

In [2]:
pd.read_csv('services.csv')

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,None,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,None,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
7,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
8,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
10,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
12,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
13,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
16,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,None,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,None,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [3]:
pd.read_csv('services.csv', header=None)

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
1,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
2,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
3,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
4,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,None,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
5,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
6,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,None,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
7,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
8,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
9,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
10,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
11,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
12,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
13,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
14,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
15,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
16,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
17,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
18,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
19,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
20,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
21,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
22,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,None,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
23,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,None,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [4]:
df = pd.read_csv('services.csv')

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
df.columns

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='object')

In [7]:
list(df.columns)

['id',
 'location_id',
 'program_id',
 'accepted_payments',
 'alternate_name',
 'application_process',
 'audience',
 'description',
 'eligibility',
 'email',
 'fees',
 'funding_sources',
 'interpretation_services',
 'keywords',
 'languages',
 'name',
 'required_documents',
 'service_areas',
 'status',
 'wait_time',
 'website',
 'taxonomy_ids']

In [8]:
df.head()

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,None,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN

In [9]:
df.head(3)

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN

In [10]:
df.tail()

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,None,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,None,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [11]:
df.tail(3)

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,None,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,None,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [12]:
df.dtypes

id                           int64
location_id                  int64
program_id                 float64
accepted_payments           object
alternate_name              object
application_process         object
audience                    object
description                 object
eligibility                 object
email                       object
fees                        object
funding_sources             object
interpretation_services     object
keywords                    object
languages                   object
name                        object
required_documents          object
service_areas               object
status                      object
wait_time                   object
website                     object
taxonomy_ids                object
dtype: object

In [13]:
df.columns

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='object')

In [16]:
df['alternate_name']

0                       NaN
1                       NaN
2                       NaN
3                       NaN
4                       NaN
5                       NaN
6                       NaN
7                       NaN
8                       NaN
9                       NaN
10                      NaN
11                      NaN
12                      NaN
13                      NaN
14                      NaN
15                      NaN
16                      NaN
17                      NaN
18                      NaN
19                      NaN
20                      NaN
21    Fotos para pasaportes
22                      NaN
Name: alternate_name, dtype: object

In [17]:
type(df.alternate_name)

pandas.core.series.Series

In [19]:
list(df.alternate_name)

[nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Fotos para pasaportes',
 nan]

In [22]:
type(df[['alternate_name']])

pandas.core.frame.DataFrame

In [23]:
df[['keywords', 'status']]

                                             keywords    status
0   ADULT PROTECTION AND CARE SERVICES, Meal Sites...    active
1   EMPLOYMENT/TRAINING SERVICES, Job Development,...    active
2   Geriatric Counseling, Older Adults, Gay, Lesbi...    active
3   INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...    active
4      COMMUNITY SERVICES, Speakers, Automobile Loans    active
5   ADULT PROTECTION AND CARE SERVICES, In-Home Su...    active
6   ADULT PROTECTION AND CARE SERVICES, Adult Day ...    active
7   ADULT PROTECTION AND CARE SERVICES, Meal Sites...    active
8   EDUCATION SERVICES, Library, Libraries, Public...    active
9   EDUCATION SERVICES, Library, Libraries, Public...    active
10  EDUCATION SERVICES, Library, Libraries, Public...    active
11  EDUCATION SERVICES, Adult, Alternative, Litera...    active
12  EDUCATION SERVICES, Library, Libraries, Public...    active
13  COMMUNITY SERVICES, Interpretation/Translation...    active
14  ALCOHOLISM SERVICES, Residential Care, DRUG AB...    active
15  COMMODITY SERVICES, Clothing/Personal Items, C...    active
16  COMMODITY SERVICES, Clothing/Personal Items, C...    active
17  HEALTH SERVICES, Outpatient Care, Community Cl...    active
18  HEALTH SERVICES, Outpatient Care, Community Cl...    active
19                                                NaN   defunct
20                                                NaN  inactive
21                                    Salud, Medicina    active
22         Ruby on Rails/Postgres/Redis, testing, wic    active

In [25]:
df1 = pd.read_csv('Financial Sample.xlsx')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 15: invalid start byte

In [26]:
df2 =pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

In [27]:
df2

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [28]:
type(df2)

pandas.core.frame.DataFrame

In [30]:
df2.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [31]:
df.head(3)

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN

In [32]:
df.tail(1)

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,None,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [33]:
df['audience']

0     Older adults age 55 or over, ethnic minorities...
1          Residents of San Mateo County age 55 or over
2     Older adults age 55 or over who can benefit fr...
3     Parents, children, families with problems of c...
4     Low-income working families with children tran...
5                                               Any age
6     Older adults who have memory or sensory loss, ...
7     Senior citizens age 60 or over, disabled indiv...
8        Ethnic minorities, especially Spanish speaking
9                                                   NaN
10                                                  NaN
11    Adults, parents, children in 1st-12th grades i...
12                                                  NaN
13    Individuals or families with low or no income ...
14    Adult alcoholic/drug addictive men and women w...
15                                                  NaN
16                                                  NaN
17                                                  NaN
18                                                  NaN
19                                                  NaN
20                                                  NaN
21    Profit and nonprofit businesses, the public, m...
22    Second service and nonprofit businesses, the p...
Name: audience, dtype: object

In [37]:
df[['location_id', 'audience']]

    location_id                                           audience
0             1  Older adults age 55 or over, ethnic minorities...
1             2       Residents of San Mateo County age 55 or over
2             3  Older adults age 55 or over who can benefit fr...
3             4  Parents, children, families with problems of c...
4             5  Low-income working families with children tran...
5             6                                            Any age
6             7  Older adults who have memory or sensory loss, ...
7             8  Senior citizens age 60 or over, disabled indiv...
8             9     Ethnic minorities, especially Spanish speaking
9            10                                                NaN
10           11                                                NaN
11           12  Adults, parents, children in 1st-12th grades i...
12           13                                                NaN
13           14  Individuals or families with low or no income ...
14           15  Adult alcoholic/drug addictive men and women w...
15           16                                                NaN
16           17                                                NaN
17           18                                                NaN
18           19                                                NaN
19           20                                                NaN
20           21                                                NaN
21           22  Profit and nonprofit businesses, the public, m...
22           22  Second service and nonprofit businesses, the p...

In [38]:
df2.to_csv('test.csv')    # it save with indexes

In [39]:
df2.to_csv('test1.csv', index=False)

In [41]:
!pip install lxml

Collecting lxml
  Downloading lxml-5.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 59.8 MB/s eta 0:00:0000:0100:01
Installing collected packages: lxml
Successfully installed lxml-5.1.0

In [20]:
import pandas as pd
import lxml
df3 = pd.read_html('https://www.basketball-reference.com/leagues/NBA_2023_shooting.html', skiprows=1)

In [21]:
type(df3)

list

In [22]:
df3

[      Rk                    Player Pos Age   Tm   G    MP   FG% Dist.  \
        1          Precious Achiuwa   C  23  TOR  55  1140  .485   9.7
 0      2              Steven Adams   C  29  MEM  42  1133  .597   2.6
 1      3               Bam Adebayo   C  25  MIA  75  2598  .540   7.3
 2      4              Ochai Agbaji  SG  22  UTA  59  1209  .427  16.9
 3      5              Santi Aldama  PF  22  MEM  77  1682  .470  14.6
 4      6  Nickeil Alexander-Walker  SG  24  TOT  59   884  .444  16.9
 ..   ...                       ...  ..  ..  ...  ..   ...   ...   ...
 699  535            Thaddeus Young  PF  34  TOR  54   795  .545   7.9
 700  536                Trae Young  PG  24  ATL  73  2541  .429  14.9
 701  537            Omer Yurtseven   C  24  MIA   9    83  .593  10.3
 702  538               Cody Zeller   C  30  MIA  15   217  .627   4.4
 703  539               Ivica Zubac   C  25  LAC  76  2170  .634   3.3

     Unnamed: 9_level_0  ...     3P Unnamed: 26_level_0  %FGA    #  \
     Unnamed: 9_level_1  ...   .966 Unnamed: 26_level_1  .141   49
 0                  NaN  ...    NaN                 NaN  .163   41
 1                  NaN  ...  1.000                 NaN  .136  139
 2                  NaN  ...   .988                 NaN  .054   17
 3                  NaN  ...   .968                 NaN  .118   54
 4                  NaN  ...   .803                 NaN  .010    2
 ..                 ...  ...    ...                 ...   ...  ...
 699                NaN  ...  1.000                 NaN  .051   10
 700                NaN  ...   .318                 NaN  .000    0
 701                NaN  ...  1.000                 NaN  .074    1
 702                NaN  ...    NaN                 NaN  .153    8
 703                NaN  ...    NaN                 NaN  .286  130

     Unnamed: 29_level_0   %3PA   3P% Unnamed: 32_level_0 Att.  #
     Unnamed: 29_level_1   .444  .250 Unnamed: 32_level_1    1  0
 0                   NaN  1.000  .000                 NaN    0  0
 1                   NaN   .000   NaN                 NaN    1  0
 2                   NaN   .412  .457                 NaN    0  0
 3                   NaN   .391  .365                 NaN    1  0
 4                   NaN   .277  .386                 NaN    2  0
 ..                  ...    ...   ...                 ...  ... ..
 699                 NaN   .706  .208                 NaN    1  0
 700                 NaN   .050  .304                 NaN    2  0
 701                 NaN   .571  .500                 NaN    0  0
 702                 NaN   .500  .000                 NaN    0  0
 703                 NaN   .000   NaN                 NaN    1  0

 [704 rows x 35 columns]]

In [23]:
df4 = df3[0]

In [24]:
type(df4)

pandas.core.frame.DataFrame

In [25]:
df4

,Rk,Player,Pos,Age,Tm,G,MP,FG%,Dist.,Unnamed: 9_level_0,...,3P,Unnamed: 26_level_0,%FGA,#,Unnamed: 29_level_0,%3PA,3P%,Unnamed: 32_level_0,Att.,#
,1,Precious Achiuwa,C,23,TOR,55,1140,.485,9.7,Unnamed: 9_level_1,...,.966,Unnamed: 26_level_1,.141,49,Unnamed: 29_level_1,.444,.250,Unnamed: 32_level_1,1,0
0,2,Steven Adams,C,29,MEM,42,1133,.597,2.6,NaN,...,NaN,NaN,.163,41,NaN,1.000,.000,NaN,0,0
1,3,Bam Adebayo,C,25,MIA,75,2598,.540,7.3,NaN,...,1.000,NaN,.136,139,NaN,.000,NaN,NaN,1,0
2,4,Ochai Agbaji,SG,22,UTA,59,1209,.427,16.9,NaN,...,.988,NaN,.054,17,NaN,.412,.457,NaN,0,0
3,5,Santi Aldama,PF,22,MEM,77,1682,.470,14.6,NaN,...,.968,NaN,.118,54,NaN,.391,.365,NaN,1,0
4,6,Nickeil Alexander-Walker,SG,24,TOT,59,884,.444,16.9,NaN,...,.803,NaN,.010,2,NaN,.277,.386,NaN,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699,535,Thaddeus Young,PF,34,TOR,54,795,.545,7.9,NaN,...,1.000,NaN,.051,10,NaN,.706,.208,NaN,1,0
700,536,Trae Young,PG,24,ATL,73,2541,.429,14.9,NaN,...,.318,NaN,.000,0,NaN,.050,.304,NaN,2,0
701,537,Omer Yurtseven,C,24,MIA,9,83,.593,10.3,NaN,...,1.000,NaN,.074,1,NaN,.571,.500,NaN,0,0
702,538,Cody Zeller,C,30,MIA,15,217,.627,4.4,NaN,...,NaN,NaN,.153,8,NaN,.500,.000,NaN,0,0
703,539,Ivica Zubac,C,25,LAC,76,2170,.634,3.3,NaN,...,NaN,NaN,.286,130,NaN,.000,NaN,NaN,1,0

In [27]:
df4.head()

,Rk,Player,Pos,Age,Tm,G,MP,FG%,Dist.,Unnamed: 9_level_0,...,3P,Unnamed: 26_level_0,%FGA,#,Unnamed: 29_level_0,%3PA,3P%,Unnamed: 32_level_0,Att.,#
,1,Precious Achiuwa,C,23,TOR,55,1140,.485,9.7,Unnamed: 9_level_1,...,.966,Unnamed: 26_level_1,.141,49,Unnamed: 29_level_1,.444,.250,Unnamed: 32_level_1,1,0
0,2,Steven Adams,C,29,MEM,42,1133,.597,2.6,NaN,...,NaN,NaN,.163,41,NaN,1.000,.000,NaN,0,0
1,3,Bam Adebayo,C,25,MIA,75,2598,.540,7.3,NaN,...,1.000,NaN,.136,139,NaN,.000,NaN,NaN,1,0
2,4,Ochai Agbaji,SG,22,UTA,59,1209,.427,16.9,NaN,...,.988,NaN,.054,17,NaN,.412,.457,NaN,0,0
3,5,Santi Aldama,PF,22,MEM,77,1682,.470,14.6,NaN,...,.968,NaN,.118,54,NaN,.391,.365,NaN,1,0
4,6,Nickeil Alexander-Walker,SG,24,TOT,59,884,.444,16.9,NaN,...,.803,NaN,.010,2,NaN,.277,.386,NaN,2,0

In [28]:
df4.tail(2)

,Rk,Player,Pos,Age,Tm,G,MP,FG%,Dist.,Unnamed: 9_level_0,...,3P,Unnamed: 26_level_0,%FGA,#,Unnamed: 29_level_0,%3PA,3P%,Unnamed: 32_level_0,Att.,#
,1,Precious Achiuwa,C,23,TOR,55,1140,.485,9.7,Unnamed: 9_level_1,...,.966,Unnamed: 26_level_1,.141,49,Unnamed: 29_level_1,.444,.250,Unnamed: 32_level_1,1,0
702,538,Cody Zeller,C,30,MIA,15,217,.627,4.4,NaN,...,NaN,NaN,.153,8,NaN,.500,.000,NaN,0,0
703,539,Ivica Zubac,C,25,LAC,76,2170,.634,3.3,NaN,...,NaN,NaN,.286,130,NaN,.000,NaN,NaN,1,0

In [29]:
df4.dtypes

Rk                   1                       object
Player               Precious Achiuwa        object
Pos                  C                       object
Age                  23                      object
Tm                   TOR                     object
G                    55                      object
MP                   1140                    object
FG%                  .485                    object
Dist.                9.7                     object
Unnamed: 9_level_0   Unnamed: 9_level_1     float64
2P                   .733                    object
0-3                  .381                    object
3-10                 .262                    object
10-16                .069                    object
16-3P                .012                    object
3P                   .267                    object
Unnamed: 16_level_0  Unnamed: 16_level_1    float64
2P                   .564                    object
0-3                  .734                    object
3-10                 .406                    object
10-16                .286                    object
16-3P                .200                    object
3P                   .269                    object
Unnamed: 23_level_0  Unnamed: 23_level_1    float64
2P                   .623                    object
3P                   .966                    object
Unnamed: 26_level_0  Unnamed: 26_level_1    float64
%FGA                 .141                    object
#                    49                      object
Unnamed: 29_level_0  Unnamed: 29_level_1    float64
%3PA                 .444                    object
3P%                  .250                    object
Unnamed: 32_level_0  Unnamed: 32_level_1    float64
Att.                 1                       object
#                    0                       object
dtype: object

In [30]:
df4.columns

MultiIndex([(                 'Rk',                   '1'),
            (             'Player',    'Precious Achiuwa'),
            (                'Pos',                   'C'),
            (                'Age',                  '23'),
            (                 'Tm',                 'TOR'),
            (                  'G',                  '55'),
            (                 'MP',                '1140'),
            (                'FG%',                '.485'),
            (              'Dist.',                 '9.7'),
            ( 'Unnamed: 9_level_0',  'Unnamed: 9_level_1'),
            (                 '2P',                '.733'),
            (                '0-3',                '.381'),
            (               '3-10',                '.262'),
            (              '10-16',                '.069'),
            (              '16-3P',                '.012'),
            (                 '3P',                '.267'),
            ('Unnamed: 16_level_0', 'Unnamed: 16_level_1'),
            (                 '2P',                '.564'),
            (                '0-3',                '.734'),
            (               '3-10',                '.406'),
            (              '10-16',                '.286'),
            (              '16-3P',                '.200'),
            (                 '3P',                '.269'),
            ('Unnamed: 23_level_0', 'Unnamed: 23_level_1'),
            (                 '2P',                '.623'),
            (                 '3P',                '.966'),
            ('Unnamed: 26_level_0', 'Unnamed: 26_level_1'),
            (               '%FGA',                '.141'),
            (                  '#',                  '49'),
            ('Unnamed: 29_level_0', 'Unnamed: 29_level_1'),
            (               '%3PA',                '.444'),
            (                '3P%',                '.250'),
            ('Unnamed: 32_level_0', 'Unnamed: 32_level_1'),
            (               'Att.',                   '1'),
            (                  '#',                   '0')],
           )

In [32]:
df4[['Rk'	,'Player',	'Pos',	'Age'	,'Tm'	,'G']]

      Rk                    Player Pos Age   Tm   G
       1          Precious Achiuwa   C  23  TOR  55
0      2              Steven Adams   C  29  MEM  42
1      3               Bam Adebayo   C  25  MIA  75
2      4              Ochai Agbaji  SG  22  UTA  59
3      5              Santi Aldama  PF  22  MEM  77
4      6  Nickeil Alexander-Walker  SG  24  TOT  59
..   ...                       ...  ..  ..  ...  ..
699  535            Thaddeus Young  PF  34  TOR  54
700  536                Trae Young  PG  24  ATL  73
701  537            Omer Yurtseven   C  24  MIA   9
702  538               Cody Zeller   C  30  MIA  15
703  539               Ivica Zubac   C  25  LAC  76

[704 rows x 6 columns]

In [34]:
df4.to_csv('html_data.csv', index=False)